### ISSUE TITLE
Update official docker image

### ISSUE THREAD

**Issue by VladRassokhin** [canonical/snapcraft#4410]
### What needs to get done

Release a new version of docker image https://hub.docker.com/r/snapcore/snapcraft/tags

### Why it needs to get done

The current `:stable` was published 3 years ago, it bundles "snapcraft, version 4.4.4" which doesn't support the `--build-for` option for `snapcraft snap` command.
`:latest` has "snapcraft, version 4.6.2.post12+gitae6e8b70", which also lacks `--build-for`.

Without `--build-for`, I cannot proceed to generate multi-arch (amd64/arm64) snaps, since I'm using one `snapcraft.yaml` for two per-arch snaps.

While I can build a custom docker image, I'd prefer to use an **official one**.
For custom docker image I've used https://github.com/snapcore/snapcraft/pull/4290 as the base, with some additional changes in my fork, `dockerfile` branch: https://github.com/snapcore/snapcraft/compare/main...VladRassokhin:snapcraft:dockerfile  (I can send those commits as PR if you need)

Related issue in IntelliJ IDEA tracker: https://youtrack.jetbrains.com/issue/IDEA-253637/snapcraft.io-Add-ARM64-snap-package-for-Idea-based-IDEs.

**Comment by ARostovsky** [comment]
+1

**Comment by mikemarquez** [comment]
+1 Can this please be addressed?  The fact that the image is using Xenial and several major versions behind is concerning.  I would even be happy with an update on the status of this.

**Comment by nuxy** [comment]
+1

**Comment by tigarmo** [comment]
Hi folks. A belated update here is that our new [snapcraft-rocks](https://github.com/canonical/snapcraft-rocks) initiative should satisfy the need for up-to-date Docker images. We already have rocks for Snapcraft 7 and 8 and in the coming weeks will be publishing the images somewhere (I'll update here when it's done).

**Comment by tigarmo** [comment]
> (I'll update here when it's done).

Following up on this! Here's the announcement: https://forum.snapcraft.io/t/snapcraft-rocks-oci-images/39581

**Comment by mr-cal** [comment]
Closing this issue now that [`snapcraft-rocks`](https://github.com/canonical/snapcraft-rocks) is publishing OCI images [here](https://github.com/canonical/snapcraft-rocks/pkgs/container/snapcraft).

**Comment by VladRassokhin** [comment]
There's a compatibility problem between the old image and the new one: one has to remove first `snapcraft` argument, since new image has wrapper which does `exec /bin/snapcraft "$@"`

**Comment by VladRassokhin** [comment]
@mr-cal @tigarmo Overall, new snapcraft-rocks image doesn't seem to provide anything useful compared to Dockerfile from #4290+fixes. 
Even worse: 
1. one cannot build it without using Ubuntu as host and several other Ubuntu-specific tools and packages. 
2. It still lacks an arm64 version.
3. `--workdir` is not supported, and the first argument should be dropped, meaning no 'drop-in' replacement possible.
