### ISSUE TITLE
Support a Snapcraft ROCK

### ISSUE THREAD

**Issue by tigarmo** [canonical/snapcraft#4476]
### What needs to get done

Create a Rockcraft project to deploy Snapcraft as an OCI image

### Why it needs to get done

The current Docker image is quite out of date

**Comment by mr-cal** [comment]
The repo for snapcraft rocks can be found here: https://github.com/canonical/snapcraft-rocks

The images are published to: https://github.com/canonical/snapcraft-rocks/pkgs/container/snapcraft
