### ISSUE TITLE
remote build: timer resets every 30 seconds

### ISSUE THREAD

**Issue by lengau** [canonical/snapcraft#4521]
### Bug Description

Running remote build on a core22 snap resets the spinner every 30 seconds	

### To Reproduce

1. `git clone https://github.com/lengau/ruff-snap`
2. `snapcraft remote-build`

### Environment

Remote build from Ubuntu mantic

### snapcraft.yaml

```shell
n/a
```

### Relevant log output

```shell
n/a
```

**Comment by mr-cal** [comment]
This happens because snapcraft queries launchpad every 30 seconds for the build status and outputs a new build status message.

If the build status has not changed, perhaps snapcraft should not re-log the same message to prevent the timer from resetting.

**Comment by lengau** [comment]
I'm guessing fixing https://github.com/canonical/craft-cli/issues/138 will resolve this?

**Comment by mr-cal** [comment]
Oh yeah, fixing this in craft-cli would be a better solution than my proposed workaround.

**Comment by mr-cal** [comment]
That fix (https://github.com/canonical/craft-cli/pull/209) is waiting for a review from @tigarmo

**Comment by mr-cal** [comment]
Fixed via https://github.com/canonical/craft-cli/pull/209
