### ISSUE TITLE
edge/components not available on arm64

### ISSUE THREAD

**Issue by xnox** [canonical/snapcraft#4590]
### Bug Description

latest/edge/components fails to install on arm64, and we do need components on amd64 & arm64 to keep parity, whilst the focus is on amd64 only.

Mostly because we use one recipe to build all arches..... and ideally want the same recipe for all arches.

### To Reproduce

https://launchpad.net/~canonical-kernel-snaps/+snap/noble--linux--pc-kernel--edge--1+2

Trigger build in launchpad with snapcraft requested from latest/edge/components channel

### Environment

Launchpad

### snapcraft.yaml

```shell
name: pc-kernel
```

### Relevant log output

```shell
error: requested a non-existing branch on latest/edge for snap "snapcraft":
       components
Install failed
```

**Comment by dilyn-corner** [comment]
I would also like to request a build for RISC-V.

**Comment by mr-cal** [comment]
Component support is available in Snapcraft 8 on all architectures
