### ISSUE TITLE
Support of Incus as snap builder backbone

### ISSUE THREAD

**Issue by KhazAkar** [canonical/snapcraft#4829]
### What needs to get done

1. Check differences between LXD and Incus
2. Implement interfaces to talk to incus, based off LXD
3. Add CLI `--use-incus` to match already existing `use-lxd`

### Why it needs to get done

Incus seems to be a great alternative to LXD after moving LXD under Canonical umbrella, so having backend allowing to build snaps outside that umbrella, under Linuxcontainers.org, seems like a good match.

**Comment by mr-cal** [comment]
Thanks for the suggestion, there is some discussion on this topic in the forums: https://forum.snapcraft.io/t/use-incus-instead-of-lxd-to-build-snaps/38682/5?u=mr_cal

**Comment by mr-cal** [comment]
I'm going to close this issue.  Not because it is invalid, but because the strategy is undeveloped and the forum is the best place for that discussion.  Once there is an approved strategy, we can create issues in [craft-providers](https://github.com/canonical/craft-providers) to implement it.
