### ISSUE TITLE
Migrated my app to core24. Platforms is declared only as amd64 and arm64 but remote build is trying to build for all platforms.

### ISSUE THREAD

**Issue by sergiusens** [canonical/snapcraft#4867]
@mr-cal Just migrated my app to core24. Platforms is declared only as amd64 and arm64 but remote build is trying to build for all platforms. 
https://github.com/t4saha/stellarium-snap

![Screenshot_20240621-103608](https://github.com/canonical/snapcraft/assets/34002960/827a9d15-cf4a-4a95-8f54-47903b0394d5)

_Originally posted by @t4saha in https://github.com/canonical/snapcraft/issues/4630#issuecomment-2182008893_

**Comment by mr-cal** [comment]
This is a known bug described in #4858 and is waiting on https://github.com/canonical/craft-platforms/issues/5 to be completed.

**Comment by mr-cal** [comment]
This bug should be fixed now that Launchpad is parsing the `platforms` keyword for `core24` snaps via https://bugs.launchpad.net/launchpad/+bug/2072622.
