### ISSUE TITLE
Add regex validator for app commands

### ISSUE THREAD

**Issue by mr-cal** [canonical/snapcraft#4999]
### What needs to get done

Add a validator for `command`, `stop-command`, `reload-command`, `post-stop-command`, and `bus-name` to match `snapd`'s [validation](https://github.com/canonical/snapd/blob/0706e2d0b20ae2bf030863f142b8491b66e80bcb/snap/validate.go#L756).

### Why it needs to get done

Using an `=` sign is a common mistake:

```yaml
apps:
  my-app:
     command: my-app --parameter=foo
```

* A user has to run the entire lifecycle to receive an error that could have been caught when validating.
* The error message from snapd isn't great.

**Comment by medubelko** [comment]
Let's make sure to enumerate the character limitations this imposes on the schema. Citing the (unedited) old schema doc:

> The command must consist only of alphanumeric characters, spaces, and the following special characters: `/`, `.`, `_`, `#`, `:`, `$`, `-`. If other characters are required, a wrapper script should be used for the command.
